export { default as authController } from './auth.controller'
export { default as userController } from './user.controller'
export { default as uploadController } from './upload.controller'
export { default as productController } from './product.controller'
export { default as orderController } from './order.controller'
